spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpazone
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

  jpa:
#    hibernate.hbm2ddl.auto: create
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true #System.out 으로 보이는 로그들
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #Logger로 보이는 로그들
#    org.hibernate.type: trace

# mybatis
mybatis:
  # resources/mybatis/mapper/ 에 있는 모든 xml 파일
  mapper-locations: mybatis/mapper/*.xml
  #mybatis.type-aliases-package=jpa.jpazone.mybatis.dto